title = "Eclipse"
base_url = "https://beucismis.github.io/eclipse"
description = "A dark theme for Zola"
generate_feed = true


[extra]
author = "beucismis"
eclipse_menu = [
    {url = "$BASE_URL", name = "/home"},
    {url = "$BASE_URL/projects", name = "/projects"},
]
eclipse_profile = [
    {title = "GitHub", url = "https://github.com/example"},
    {title = "GitLab", url = "https://gitlab.com/example"},
]
eclipse_contact = [
    {title = "E-mail", url = "me@example.com"},
]
eclipse_button = [
    {url = "/button/gnu.png"},
    {url = "/button/linux.png"},
    {url = "/button/debian.png"},
]
