name = "eclipse"
description = "A dark theme for Zola"
license = "MIT"
homepage = "https://github.com/beucismis/eclipse"
min_version = "0.0.1"
demo = "https://beucismis.github.io/eclipse"

[author]
name = "beucismis"
homepage = "https://github.com/beucismis"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
